baseURL = "https://simplere.netlify.app"
languageCode = "en-us"
summarylength = 20
[[menu.main]]
name = "Featured Listings"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
category = "categories"
tag = "tags"
